### ISSUE TITLE
Hi, what is this & what it can do?

### ISSUE THREAD

**Issue by nadiamode** [bandoche/pyLine#1]
i'm curious, is this line app api? i search line app api but i can't find any documents related to LINE

**Comment by bandoche** [comment]
Hi nadiamode. 
As far as I know, there is no offical API for LINE. And of course, this is not official API of LINE app.

**Comment by bandoche** [comment]
And you can communicate with LINE via this script and thrift data.

**Comment by nadiamode** [comment]
i think this is good script but it beyond my knowledge to handle it, i know just simple php things :p
