### ISSUE TITLE
How to "Modified Host for Line domain"?

### ISSUE THREAD

**Issue by LiYouliang** [bandoche/pyLine#4]
In the section of "How to discover" in the README file, you said first "Modified Host for Line domain to a lazy server". But how did you do that? Does that mean to change the host in the Python Client? I see the code below in the Python Client file. Could you please help to make it more clear? Thank you so much for you cool project and help.

```
    # Make socket
    # make Reverse proxy for NHN Line (gd2.line.naver.jp) if you want to see the traffic. otherwise, just connect to https://gd2.line.naver.jp

    transport = THttpClient.THttpClient('http://localhost:8080/api/v4/TalkService.do')
    # transport = THttpClient.THttpClient('http://localhost:30303/')
```

**Comment by bandoche** [comment]
What `Modified host for Lline domain` means modify /etc/hosts file for all line related domain to localhost (gd2.line.naver.jp and else).
Maybe title `How to discover` should be changed as `How I discover`.

**Comment by bandoche** [comment]
Tracking DNS queries from macOS LINE client, domains that LINE uses can be obtained. Then modify hosts file for whole list to 127.0.0.1 and running HTTPS transparent proxy (with mitmproxy for HTTP transparent proxy and nginx for SSL layer)

**Comment by LiYouliang** [comment]
Thank you so much for your speedy reply! It is so clear now. Coincidentally I did the almost the same thing but I was just using HTTP proxy (with mitmproxy) for chrome LINE client, so I do not need to change the DNS.

**Comment by LiYouliang** [comment]
According to the docs of mitmproxy: [About Certificates](http://docs.mitmproxy.org/en/latest/certinstall.html). It indicates that Mitmproxy can decrypt encrypted traffic on the fly, as long as the client trusts its built-in certificate authority. So I think it is not need with nginx for SSL layer, I can get the decrypted traffic directly. What do you think about that?

Actually I have got the traffic but I could not read it and not sure if it is decrypted since I am a newbie to thrift.

**Comment by bandoche** [comment]
`mitmproxy` you linked - same as I used - offer HTTPS proxy for regular mode, but not for transparent mode. http://docs.mitmproxy.org/en/latest/modes.html
That's why I make SSL Layer for nginx.

**Comment by bandoche** [comment]
And in your case for Chrome LINE app, it will follow proxy setting on system(Windows in IE setting, macOS for System preferences/Networking). Unfortunately, LINE macOS app I tested won't follow system's proxy setting. Thanks why the architect I build is so weird 😞

**Comment by LiYouliang** [comment]
Ah hah, ok, I see. Thanks so much for your explanation about regular mode and transparent mode. Maybe it is the reason cause I could not read the data. I will learn about it.
